config/routes.rb
#coding: utf-8
# GraphsController
# Author:: Kazuko Ohmura
# Date:: 2013.07.25

Shirokane::Application.routes.draw do
  root 'dashboards#index'
  
  #get "password_resets/new"
  resources :password_resets
  
  resources :login
  resources :users
  resources :graphs do
    member do
      get 'csvexport'
      post 'setday'
    end
  end
  
    # You can have the root of your site routed with "root"
    # root 'welcome#index'
    

  #管理画面用
  namespace :admin do
    resources :login
    resources :users
    resources :graphs
    resources :groups
    resources :home
    resources :settings
    resources :groupgraphs do
      member do
        get 'list'
      end
    end
    root 'home#index'
  end
end

app/views/admin/common/_footer.html.erb
</div>
<!-- administrator wrapper end -->
<!-- administrator footer start -->
<div id="footer">
<!-- コピーライト / 著作権表示 -->
<h1>Copyright©SIOS Technology, Inc. All Rights Reserved</h1>
</div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript">
  var htmlHeight = $("html").height();
  var contentHeight = $("#content").innerHeight();
  $(function() {
    if(htmlHeight > contentHeight){
      $("#wrapper").css("height",htmlHeight-150+"px");
      $("#content").css("height",htmlHeight-150+"px");
    }
  });
  $(function() {
    $(window).resize(function(){
      var htmlHeight = $("html").height();
      $("#wrapper").css("height",htmlHeight-150+"px");
      $("#content").css("height",htmlHeight-150+"px");
    });
  });
</script>

<!-- administrator footer end -->

app/views/admin/common/_header.html.erb
<!-- administrator header start -->
<div id="header_admin">
	<div id="logo">
		<h1><%= link_to(admin_root_path) do %><%= $settings['title'] %>&nbsp;<%= t('adminview') %><% end %></h1>
	</div>
	<% if admin_current_user != nil %>
	<div id="header_admin_contents">
	 <ul>
	  <li class="user"><i class="icon-user"></i>&nbsp;<%= admin_current_user.title %></li>
	  <li class="logout">
	  	<%= link_to(admin_login_path(admin_current_user.id), :data =>{:confirm => t('logout_message')}, :method => :delete) do %>
	  	<i class="icon-lock"></i>&nbsp;<%= t('logout') %>
	  	<% end %>
	  </li>
	  </ul>
	</div>
	<% end %>
</div>
<!-- administrator header end -->
<!-- administrator wrapper start -->
<% if admin_current_user != nil %>
<div id="wrapper">
<% else %>
<div id="wrapper" class="login">
<% end %>

app/views/admin/common/_sidebar.html.erb
<!-- administrator navigation start -->
<div id="navigation">
	<ul class="cds-navi">
		<li<% if params[:controller] == "admin/home" %> class="select"<% end %>><%= link_to(admin_root_path) do %><i class="icon-desktop"></i>&nbsp;<%= t('title_home') %><% end %></li>
		<li<% if params[:controller] == "admin/users" %> class="select"<% end %>><%= link_to(admin_users_path) do %><i class="icon-user"></i>&nbsp;<%= t('menu_user') %><% end %></li>
		<li<% if params[:controller] == "admin/groups" || params[:controller] == "admin/groupgraphs" %> class="select"<% end %>><%= link_to(admin_groups_path) do %><i class="icon-group"></i>&nbsp;<%= t('menu_group') %><% end %></li>
		<li<% if params[:controller] == "admin/graphs" %> class="select"<% end %>><%= link_to(admin_graphs_path) do %><i class="icon-bar-chart"></i>&nbsp;<%= t('menu_graph') %><% end %></li>
		<li<% if params[:controller] == "admin/settings" %> class="select"<% end %>><%= link_to(admin_settings_path) do %><i class="icon-cog"></i>&nbsp;<%= t('menu_setting') %><% end %></li>
	</ul>
</div>
<!-- administrator navigation end -->