config/routes.rb
#coding: utf-8
# GraphsController
# Author:: Kazuko Ohmura
# Date:: 2013.07.25

Shirokane::Application.routes.draw do
  root 'dashboards#index'
  
  #get "password_resets/new"
  resources :password_resets
  
  resources :login
  resources :users
  resources :graphs do
    member do
      get 'csvexport'
      post 'setday'
    end
  end
  
    # You can have the root of your site routed with "root"
    # root 'welcome#index'
    

  #管理画面用
  namespace :admin do
    resources :login
    resources :users
    resources :graphs
    resources :groups
    resources :home
    resources :settings
    resources :groupgraphs do
      member do
        get 'list'
      end
    end
    root 'home#index'
  end
end

app/models/admin/graph.rb
#coding: utf-8
# Admin::Graph Model
# Author:: Kazuko Ohmura
# Date:: 2013.07.25

# 管理用グラフモデル
class Admin::Graph < Graph
  #入力チェック
  # 名前
  validates :name,
    :presence => true,
    :uniqueness=>true,
    :length=>{:maximum=>20},
    :format=>{:with => /^[a-zA-Z0-9]+$/,:multiline=>true,:message=> I18n.t('error_graph_name_format_message')},
      :Graphstable=>true

  validates :title, :presence => true                           # 表示名
  validates :analysis_type,  :presence => true                  # 分析タイプ（集計、平均）
  validates :graph_type,  :presence => true                     # グラフタイプ（折線、縦棒）
  validates :term,  :presence => true                           # 期間
  validates :y,  :presence => true                              # y
  validates :y_min,  :presence => true,:numericality => true                          # y最小値
  validates :y_max_time,  :presence => true,:numericality => true                     # y最大値 時間
  validates :y_max_day,  :presence => true,:numericality => true                      # y最大値 日
  validates :y_max_month,  :presence => true,:numericality => true                    # y最大値 月
  validates :useval, :presence => true,:numericality => true    # グラフに値を表示するかどうか
  validates :useshadow, :presence => true,:numericality => true # グラフに影をつけるかどうか
  validates :usetip, :presence => true,:numericality => true    # グラフにチップをつけるかどうか
  validates :linewidth, :presence => true,:numericality => {:only_integer => true} # 線の太さ
  validates :template, :presence => true                        # テンプレート名
  validates :usepredata, :presence => true,:numericality => true    # 前日、前週、前月、前年のデータを表示するかどうか
  validates :uselastyeardata, :presence => true,:numericality => true    # １年前のデータを表示するかどうか
  
  class << self
    def set_setting
      dashboard_settings = {
        "template" => [],
        "xdatas"   => [],
        "ydatas"   => [],
        "terms"    => [],
      }
      all.each do |graph|
        # 指定テンプレート情報
        template = Graphtemplate.find_by_name(graph.template)
  
        #期間移動分
        today = Date.today
  
        # 期間の設定
        res_graph_terms = set_graph_term(graph.term, today, 0)
        today = res_graph_terms['today']
        oldday = res_graph_terms['oldday']
        # データ取得期間の設定
        today_s = today.to_s + " 23:59:59"
        oldday_s = oldday.to_s + " 00:00:00"
  
        # データの取得
        tdtable = Tdtable.graph_data(graph,term: graph.term, end: oldday_s, start: today_s)
  
        # グラフ表示用データ作成
        if tdtable
          res_graph_data = set_graph_data(tdtable, graph.term, oldday, today, res_graph_terms['stime'])
  
          dashboard_settings["template"] << template
          dashboard_settings["xdatas"]  << res_graph_data['xdata']
          dashboard_settings["ydatas"]  << res_graph_data['ydata']
          dashboard_settings["terms"] << res_graph_terms['term_s']
        end
      end

      return dashboard_settings
    end
  end
end

app/controllers/admin/graphs_controller.rb
#coding: utf-8
# GraphsController
# Author:: Kazuko Ohmura
# Date:: 2013.07.25

# グラフ管理用コントローラー
class Admin::GraphsController < AdminController
  before_filter :admin_authorize, :except => :login #ログインしていない場合はログイン画面に移動
  before_action :set_admin_graph, only: [:show, :edit, :update]
  before_action :set_select_items, only: [:index, :show,:edit, :update,:new,:create]

  # グラフ一覧画面
  def index
    @admin_graphs = Admin::Graph.all.order(:id)
  end

  # グラフ詳細画面
  def show
  end

  # グラフ新規追加
  def new
    @admin_graph = Admin::Graph.new
    @newflg = true  # フラグ
    
    # 初期値を入力
    @admin_graph.term = 2   # 期間(月)
    @admin_graph.linewidth = 2  # 線の太さ
    @admin_graph.y_min = 0 # Y軸最小値
    @admin_graph.y_max_time = 100   # Y軸最大値-時
    @admin_graph.y_max_day = 100    # Y軸最大値-日
    @admin_graph.y_max_month = 100  # Y軸最大値-月
  end

  # グラフ新規作成
  def create
    @admin_graph = Admin::Graph.new(admin_graph_params)
    @newflg = true  # フラグ

    respond_to do |format|
      if @admin_graph.save
        format.html { redirect_to @admin_graph, notice: 'Graph was successfully created.' }
        format.json { render action: 'show', status: :created, location: @admin_graph }
      else
        format.html { render action: 'new' }
        format.json { render json: @admin_graph.errors, status: :unprocessable_entity }
      end
    end
  end
        
  # グラフ編集画面
  def edit
  end

  # グラフの更新
  def update
    respond_to do |format|
      if @admin_graph.update(admin_graph_params)
        format.html { redirect_to @admin_graph, notice: 'Graph was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @admin_graph.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_graph
      @admin_graph = Admin::Graph.find(params[:id])
    end
    
    #選択肢の設定
    def set_select_items
      @graph_settings = Admin::Graph::SETTINGS

      @h_template = Hash.new()
      tmp = Admin::Graphtemplate.all.order(:name)
      tmp.each do |tt|
        @h_template[tt.name.to_s] = tt.name.to_s
      end

#      @merge = Admin::Graph.get_use_merge_graph  # グラフのマージ機能を利用させるかどうか
#      @usecreate = Admin::Graph.get_use_create_graph # グラフの新規追加機能を利用させるかどうか
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_graph_params
      params.require(:admin_graph).permit(:name, :title, :analysis_type,:graph_type, :term, :y,:y_min,:y_max_time,:y_max_day,:y_max_month,:template,:useval,:useshadow,:usetip,:linewidth,:usepredata,:uselastyeardata,:y_unit,:merge_linecolor,:merge_graph)
    end
end

app/controllers/graphs_controller.rb
#coding: utf-8
# UsersController
# Author:: Kazuko Ohmura
# Date:: 2013.07.31

require 'csv'

#グラフ表示
class GraphsController < PublichtmlController
  before_filter :authorize, :except => :login #ログインしていない場合はログイン画面に移動
  
  # グラフ用画面
  def index
    # グラフIDの指定が無い場合はルートへ移動
    redirect_to root_path
  end
  
  def setday
    begin
      today = Date.parse(params[:cal1])
    rescue => e
      # 引数付と認められなかった場合は本日の日付を設定
      today = Date.today
    end
    term = params[:term]
    add = params[:add]
    redirect_to :action => "show",:flash=>{:today=>today,:term=>term,:add=>add}
  end
  
  # csv出力処理
  def csvexport
    # 表示可能グラフチェック
    return redirect_to root_path if !check_graph_permission(params[:id]) 
    # CSVダウンロード権限チェック
    return redirect_to graph_path if check_csv_size == false

    # 指定グラフ情報
    @graph = Graph.find(params[:id])
      
    # 表示テーブル名の設定
    Tdtable.table_name = "td_" + @graph.name
    
    # 取得期間
    @start_day = params[:start];
    @end_day = params[:end];
    
    # データ取得
    @tdtable = Tdtable.where(:td_time => @start_day .. @end_day).order(:td_time)
    data = CSV.generate do |csv|
      csv << ["time", "value"]
      @tdtable.each do |td|
        csv << [td.td_time, td.td_count]
      end
    end
    
    # ファイル名
    fname =  @graph.name.to_s + "_#{Time.now.strftime('%Y_%m_%d_%H_%M_%S')}.csv"
      
    # 出力
    send_data(data, type: 'text/csv', filename: fname)
    
    # 出力データ容量記録
    today = Date.today # 今月の日付
    key = "csv_" + today.year.to_s + today.month.to_s
    tmp = Setting.find_by_name(key)
    if tmp 
      csize = tmp.parameter.to_i + data.size
      tmp.update_attribute(:parameter,csize)
    end
  end
  
  # 表示用処理
  def show
    # 表示可能グラフチェック
    return redirect_to root_path if !check_graph_permission(params[:id])
      
    # 引数の取得
    flash = params[:flash]
      
#    # 値設定
#    @h_analysis_types = {0 => t('analysis_types_sum'),1 => t('analysis_types_avg')}
#    @h_terms ={0=> t('datetime.prompts.day'),1 => t('week'),2 => t('datetime.prompts.month'),3 => t('datetime.prompts.year')}
#    @h_yesno = {0=>'no' , 1 => 'yes'}
    
    # CSVダウンロードボタン用フラグ
    @csvflg = check_csv_size
    
#    # グラフ選択枝
#    @graph_types = ['line','bar','pie']
          
    # 指定グラフ情報
    @graph = Graph.find(params[:id])

    # 指定テンプレート情報
    @template = Graphtemplate.find_by_name(@graph.template)
    
    # 表示期間指定
    if flash 
      @graph_term = flash[:term].to_i
    elsif params[:term] 
      @graph_term = params[:term].to_i
    else
      @graph_term = @graph.term
    end
    
    # 基準日付
    if flash 
      @todaydata = Date.parse(flash[:today].to_s)
    elsif params[:today] 
      @todaydata = Date.parse(params[:today].to_s)
    else
      @todaydata = Date.today - 1.day
    end
    
    # 追加期間の設定
    if flash 
      @add = flash[:add].to_i
    elsif params[:add] 
      @add = params[:add].to_i
    else
      @add = 0
    end
    
    # 期間の設定
    res_graph_terms = Graph.set_graph_term(@graph_term,@todaydata,@add)
    today = res_graph_terms['today']
    oldday = res_graph_terms['oldday']
    @term_s = res_graph_terms['term_s']
    @graphx = res_graph_terms['graphx']

    # データ取得期間の設定
    @today_s = today.to_s + " 23:59:59"
    @oldday_s = oldday.to_s + " 00:00:00"
    # データの取得
    #tdtable = td_graph_data(@graph,@graph_term,@oldday_s,@today_s)
    tdtable = Tdtable.graph_data(@graph, term: @graph_term, end: @oldday_s, start: @today_s)
    
    # グラフ表示用データ作成
    res_graph_data = Graph.set_graph_data(tdtable, @graph_term, oldday, today, res_graph_terms['stime'])
    #res_graph_data = set_graph_data(tdtable,@graph_term,oldday,today,res_graph_terms['stime'])
    @xdata = res_graph_data['xdata']
    @ydata = res_graph_data['ydata']
      
    # 期間の直前のデータ取得
    if @graph.usepredata == 1 
      pre_graph_terms = Graph.set_graph_term(@graph_term,@todaydata,@add - 1)
      # データ取得期間の設定
      ts_pre = pre_graph_terms['today'].to_s + " 23:59:59"
      os_pre = pre_graph_terms['oldday'].to_s + " 00:00:00"
      # データの取得
      #tdtable_pre = td_graph_data(@graph,@graph_term,os_pre,ts_pre)
      tdtable_pre = Tdtable.graph_data(@graph, term: @graph_term, end: os_pre, start: ts_pre)
      
      # グラフ表示用データ作成
      pre_graph_data = Graph.set_graph_data(tdtable_pre,@graph_term,pre_graph_terms['oldday'],pre_graph_terms['today'],res_graph_terms['stime'])
      @ydata_pre = pre_graph_data['ydata']
    end
    # 期間の前年のデータ取得
    if @graph_term < 3 && @graph.uselastyeardata == 1 
      # データ取得期間の設定
      tlast = today - 1.year
      olast = oldday - 1.year
      ts_last = tlast.to_s + " 23:59:59"
      os_last = olast.to_s + " 00:00:00"
      # データの取得
      #tdtable_last = td_graph_data(@graph,@graph_term,os_last,ts_last)
      tdtable_last = Tdtable.graph_data(@graph, term: @graph_term, end: os_last, start: ts_last)
      
      # グラフ表示用データ作成
      last_graph_data = Graph.set_graph_data(tdtable_last,@graph_term,olast,tlast,res_graph_terms['stime'])
      @ydata_last = last_graph_data['ydata']
    end
    
    #マージ用グラフのデータ取得
    if @graph.merge_graph != nil && @graph.merge_graph != "" 
      # 指定グラフ情報
      @m_graph = Graph.find_by_name(@graph.merge_graph)
      # データの取得
      #m_tdtable = td_graph_data(@m_graph,@graph_term,@oldday_s,@today_s)
      m_tdtable = Tdtable.graph_data(@m_graph,term: @graph_term, end: @oldday_s, start: @today_s)
      # グラフ表示用データ作成
      m_res_graph_data = Graph.set_graph_data(m_tdtable,@graph_term,oldday,today,res_graph_terms['stime'])
      @m_xdata = m_res_graph_data['xdata']
      @m_ydata = m_res_graph_data['ydata']
    end
  end


  private
  # グラフが利用可能かをチェックする
  def check_graph_permission(p_graph_id)
    return Groupgraph.exists?({:group_id=>current_user.group.id,:graph_id=>p_graph_id}) 
  end
  
  # 今月のCSVダウンロード容量チェック
  def check_csv_size
    if get_csv_size.to_i > $settings['csvdownloadsize'].to_i 
      res = false
    else
      res = true
    end
    return res
  end
  
  # 今月のCSVダウンロード容量取得
  def get_csv_size
    today = Date.today # 今月の日付
    key = "csv_" + today.year.to_s + today.month.to_s
    tmp = Setting.find_by_name(key)
    if tmp 
      # レコードが存在する
      res = tmp.parameter.to_i
    else
      # レコードが存在しない➡作成
      csvrow = Setting.new
      csvrow.name = key
      csvrow.title = key
      csvrow.parameter = 0
      csvrow.vieworder = 0
      csvrow.columntype = 0
      csvrow.save
      res = 0
    end
    return res
  end
end

app/helpers/graph_helper.rb
#coding: utf-8
# GraphHelper
# Author:: Kazuko Ohmura
# Date:: 2013.07.25

# グラフヘルパー
module GraphHelper
end

app/views/admin/graphs/_form.html.erb
<div id="setting">
<%= form_for(@admin_graph) do |f| %>
  <% if @admin_graph.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_graph.errors.count, "error") %> <%= t('error_graph_message') %></h2>

      <ul>
      <% @admin_graph.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% if @newflg %>
<h3><%= t('message_graph_new') %></h3>
<% end %>
  <div class="field">
    <%= f.label :name %><br>
    <% if @newflg %>
    	<%= f.text_field :name %>
    	<br /><%= t('message_graph_name') %>
    <% else %>
    	<%= @admin_graph.name %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :analysis_type %><br>
    <%= f.select :analysis_type,@graph_settings[:h_analysis_types].keys.map{|t| [@graph_settings[:h_analysis_types][t], t]} %>
  </div>
  
  <div class="field">
    <%= f.label :graph_type %><br>
    <%= f.select :graph_type,@graph_settings[:h_graph_types].keys.map{|t| [@graph_settings[:h_graph_types][t], t]} %>
  </div>
  
  <div class="field">
    <%= f.label :term %><br>
    <%= f.select :term,@graph_settings[:h_terms].keys.map{|t| [@graph_settings[:h_terms][t], t]} %>
  </div>
  <div class="field">
    <%= f.label :y %><br>
    <%= f.text_field :y %>
  </div>
  <div class="field">
    <%= f.label :y_min %><br>
    <%= f.text_field :y_min %>
  </div>
  <div class="field">
    <%= f.label :y_max_time %><br>
    <%= f.text_field :y_max_time %>
  </div>
  <div class="field">
    <%= f.label :y_max_day %><br>
    <%= f.text_field :y_max_day %>
  </div>
  <div class="field">
    <%= f.label :y_max_month %><br>
    <%= f.text_field :y_max_month %>
  </div>
  <div class="field">
    <%= f.label :y_unit %><br>
    <%= f.text_field :y_unit %>
  </div>
   <div class="field">
    <%= f.label :useval %><br>
    <%= f.select :useval,@graph_settings[:h_yesno].keys.map{|t| [@graph_settings[:h_yesno][t], t]} %>
  </div>
  <div class="field">
    <%= f.label :useshadow %><br>
    <%= f.select :useshadow,@graph_settings[:h_yesno].keys.map{|t| [@graph_settings[:h_yesno][t], t]} %>
  </div>
  <div class="field">
    <%= f.label :usetip %><br>
    <%= f.select :usetip,@graph_settings[:h_yesno].keys.map{|t| [@graph_settings[:h_yesno][t], t]} %>
  </div>
  <div class="field">
    <%= f.label :usepredata %><br>
    <%= f.select :usepredata,@graph_settings[:h_yesno].keys.map{|t| [@graph_settings[:h_yesno][t], t]} %>
  </div>
  <div class="field">
    <%= f.label :uselastyeardata %><br>
    <%= f.select :uselastyeardata,@graph_settings[:h_yesno].keys.map{|t| [@graph_settings[:h_yesno][t], t]} %>
  </div>
   <div class="field">
    <%= f.label :linewidth %><br>
    <%= f.number_field :linewidth %>
  </div>
   <div class="field">
    <%= f.label :template %><br>
    <%= f.select :template,@h_template.keys.map{|t| [@h_template[t], t]} %>
  </div>
  <% if Admin::Graph.get_use_merge_graph %>
  <div class="field">
    <%= f.label :merge_graph %><br>
    <%= f.text_field :merge_graph %>
  </div>
  <div class="field">
    <%= f.label :merge_linecolor %><br>
    <%= f.text_field :merge_linecolor %>
  </div>
  <% end %>
  <div class="actions">
    <%= f.submit t('helpers.submit.update'),:class=>"button_admin" %>
  </div>
<% end %>
</div>

app/views/admin/graphs/edit.html.erb
<%= render 'admin/common/header' %>
<%= render 'admin/common/sidebar' %>
<!-- administrator main content start -->
<div id="content">
<div id="sub_content">
	<h1><%= t('menu_graph') %> &nbsp;-&nbsp;<%= t('title_edit') %></h1>
</div>

<%= render 'form' %>

<%= link_to t('title_back'), admin_graphs_path,:class=>"button_link" %>

</div><!-- administrator main content end -->
<%= render 'admin/common/footer' %>

app/views/admin/graphs/index.html.erb
<%= render 'admin/common/header' %>
<%= render 'admin/common/sidebar' %>
<!-- administrator main content start -->
<div id="content">
<div id="sub_content">
	<h1><%= t('menu_graph') %></h1>
</div>
<table class="coder">
  <thead>
    <tr>
      <th><%= t('title_graph_name') %></th>
      <th><%= t('title_graph_title') %></th>
      <th><%= t('title_graph_analysis_type') %></th>
      <th><%= t('title_graph_graph_type') %></th>
      <th><%= t('title_graph_term') %></th>
      <th><%= t('title_graph_y') %></th>
      <!--
      <th><%= t('title_graph_y_min') %></th>
      <th><%= t('title_graph_y_max_time') %></th>
      <th><%= t('title_graph_y_max_day') %></th>
      <th><%= t('title_graph_y_max_month') %></th>
      <th><%= t('title_graph_useval') %></th>
      <th><%= t('title_graph_useshadow') %></th>
      <th><%= t('title_graph_usetip') %></th>
      <th><%= t('title_graph_usepredata') %></th>
      <th><%= t('title_graph_uselastyeardata') %></th>
      <th><%= t('title_graph_linewidth') %></th>-->
      <th><%= t('title_graph_template') %></th>
      <% if Admin::Graph.get_use_merge_graph %>
      <th><%= t('title_graph_merge_graph') %></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @admin_graphs.each do |admin_graph| %>
      <tr>
        <td><%= link_to admin_graph.name, edit_admin_graph_path(admin_graph) %></td>
        <td><%= admin_graph.title %></td>
        <td><%= @graph_settings[:h_analysis_types][admin_graph.analysis_type] %></td>
        <td><%= @graph_settings[:h_graph_types][admin_graph.graph_type] %></td>
        <td><%= @graph_settings[:h_terms][admin_graph.term] %></td>
        <td><%= admin_graph.y %></td>
        <!--
        <td><%= admin_graph.y_min %></td>
        <td><%= admin_graph.y_max_time %></td>
        <td><%= admin_graph.y_max_day %></td>
        <td><%= admin_graph.y_max_month %></td>
        <td><%= @graph_settings[:h_yesno][admin_graph.useval] %></td>
        <td><%= @graph_settings[:h_yesno][admin_graph.useshadow] %></td>
        <td><%= @graph_settings[:h_yesno][admin_graph.usetip] %></td>
        <td><%= @graph_settings[:h_yesno][admin_graph.usepredata] %></td>
        <td><%= @graph_settings[:h_yesno][admin_graph.uselastyeardata] %></td>
        <td><%= admin_graph.linewidth %></td>-->
        <td><%= admin_graph.template %></td>
        <% if @merge %>
        <td><%= admin_graph.merge_graph %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br />
<% if Admin::Graph.get_use_create_graph %>
<%= link_to t('title_new'), new_admin_graph_path,:class=>"button_link" %>
<% end %>

</div><!-- administrator main content end -->
<%= render 'admin/common/footer' %>

app/views/admin/graphs/new.html.erb
<%= render 'admin/common/header' %>
<%= render 'admin/common/sidebar' %>
<!-- administrator main content start -->
<div id="content">
<div id="sub_content">
	
	<h1><%= t('menu_graph') %></h1>
</div>
	<h2><%= t('title_new') %></h2>

<%= render 'form' %>

<%= link_to t('title_back'), admin_graphs_path,:class=>"button_link" %>


</div><!-- administrator main content end -->
<%= render 'admin/common/footer' %>

app/views/admin/graphs/show.html.erb
<%= render 'admin/common/header' %>
<%= render 'admin/common/sidebar' %>
<!-- administrator main content start -->
<div id="content">
<div id="sub_content">
	<h1><%= t('menu_graph') %>&nbsp;-&nbsp;<%= t('title_show') %></h1>
</div>
<div id="setting">
<p>
  <strong><%= t('title_graph_name') %></strong>
  <%= @admin_graph.name %>
</p>

<p>
  <strong><%= t('title_graph_title') %></strong>
  <%= @admin_graph.title %>
</p>

<p>
  <strong><%= t('title_graph_analysis_type') %></strong>
  <%= @graph_settings[:h_analysis_types][@admin_graph.analysis_type] %>
</p>

<p>
  <strong><%= t('title_graph_graph_type') %></strong>
  <%= @graph_settings[:h_graph_types][@admin_graph.graph_type] %>
</p>

<p>
  <strong><%= t('title_graph_term') %></strong>
  <%= @graph_settings[:h_terms][@admin_graph.term] %>
</p>

<p>
  <strong><%= t('title_graph_y') %></strong>
  <%= @admin_graph.y %>
</p>
<p>
  <strong><%= t('title_graph_y_min') %></strong>
  <%= @admin_graph.y_min %>
</p>
<p>
  <strong><%= t('title_graph_y_max_time') %></strong>
  <%= @admin_graph.y_max_time %>
</p>
<p>
  <strong><%= t('title_graph_y_max_day') %></strong>
  <%= @admin_graph.y_max_day %>
</p>
<p>
  <strong><%= t('title_graph_y_max_month') %></strong>
  <%= @admin_graph.y_max_month %>
</p>
<p>
  <strong><%= t('title_graph_unit') %></strong>
  <%= @admin_graph.y_unit %>
</p>
<p>
  <strong><%= t('title_graph_useval') %></strong>
  <%= @graph_settings[:h_yesno][@admin_graph.useval] %>
</p>
<p>
  <strong><%= t('title_graph_useshadow') %></strong>
  <%= @graph_settings[:h_yesno][@admin_graph.useshadow] %>
</p>
<p>
  <strong><%= t('title_graph_usetip') %></strong>
  <%= @graph_settings[:h_yesno][@admin_graph.usetip] %>
</p>
<p>
  <strong><%= t('title_graph_usepredata') %></strong>
  <%= @graph_settings[:h_yesno][@admin_graph.usepredata] %>
</p>
<p>
  <strong><%= t('title_graph_uselastyeardata') %></strong>
  <%= @graph_settings[:h_yesno][@admin_graph.uselastyeardata] %>
</p>
<p>
  <strong><%= t('title_graph_linewidth') %></strong>
  <%= @admin_graph.linewidth %>
</p>

<p>
  <strong><%= t('title_graph_template') %></strong>
  <%= @h_template[@admin_graph.template] %>
</p>
<% if Admin::Graph.get_use_merge_graph %>
<p>
  <strong><%= t('title_graph_merge_graph') %></strong>
  <%= @admin_graph.merge_graph %>
</p>
<p>
  <strong><%= t('title_graph_merge_linecolor') %></strong>
  <%= @admin_graph.merge_linecolor %>
</p>
<% end %>
<br /><br />
<%= link_to t('title_back'), admin_graphs_path,:class=>"button_link" %>
<%= link_to t('title_edit'), edit_admin_graph_path(@admin_graph),:class=>"button_link" %> 

</div>
</div><!-- administrator main content end -->
<%= render 'admin/common/footer' %>