config/routes.rb
#coding: utf-8
# GraphsController
# Author:: Kazuko Ohmura
# Date:: 2013.07.25

Shirokane::Application.routes.draw do
  root 'dashboards#index'
  
  #get "password_resets/new"
  resources :password_resets
  
  resources :login
  resources :users
  resources :graphs do
    member do
      get 'csvexport'
      post 'setday'
    end
  end
  
    # You can have the root of your site routed with "root"
    # root 'welcome#index'
    

  #管理画面用
  namespace :admin do
    resources :login
    resources :users
    resources :graphs
    resources :groups
    resources :home
    resources :settings
    resources :groupgraphs do
      member do
        get 'list'
      end
    end
    root 'home#index'
  end
end

app/models/admin/user.rb
#coding: utf-8
# Admin::User Model
# Author:: Kazuko Ohmura
# Date:: 2013.07.25

# 管理用ユーザモデル
class Admin::User < User
  #入力チェック
  validates :name,  :presence => true,:uniqueness=>true
  
  class << self
      # 最大登録ユーザー数
      def get_maxuser
        res = 999
        # 最大ダウンロード容量取得
        if $settings['maxuser']
          res = $settings['maxuser'].to_i
        end
        return res
      end
    end
end

app/models/user.rb
#coding: utf-8
# User Model
# Author:: Kazuko Ohmura
# Date:: 2013.07.25

# ユーザテーブル
# == 作成
# rails generate model user name:string title:string password_digest:string mail:string group_id:integer admin:boolean
class User < ActiveRecord::Base
    # パスワード用処理
    has_secure_password
    
    # グループ一覧用
    belongs_to :group
    
    # 入力チェック
    validates :title,  :presence => true
    validates :mail,  :presence => true,:uniqueness=>true, :email_format => {:message => I18n.t('error_mail_message')}

  before_create { generate_token(:auth_token) }
  
  # パスワードリセット処理
  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end
  
  # トークン作成
  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
end

app/controllers/admin/users_controller.rb
#coding: utf-8
# Admin UsersController
# Author:: Kazuko Ohmura
# Date:: 2013.07.25

# ユーザー管理
class Admin::UsersController < AdminController
  before_filter :admin_authorize, :except => :login #ログインしていない場合はログイン画面に移動
  before_action :set_admin_user, only: [:show, :edit, :update, :destroy]

  # ユーザー一覧
  def index
    @admin_users = Admin::User.all.order(:id)
    @maxuser = Admin::User.get_maxuser
  end

  # ユーザー詳細
  def show
  end

  # ユーザー新規追加
  def new
    admin_users = Admin::User.all
    if admin_users.length < Admin::User.get_maxuser
      @admin_user = Admin::User.new
    else
      redirect_to admin_users_url
    end
  end

  # ユーザー編集画面
  def edit
  end

  # ユーザー新規作成
  def create
    @admin_user = Admin::User.new(admin_user_params)

    respond_to do |format|
      if @admin_user.save
        format.html { redirect_to @admin_user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @admin_user }
      else
        format.html { render action: 'new' }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # ユーザー更新
  def update
    respond_to do |format|
      if @admin_user.update(admin_user_params)
        format.html { redirect_to @admin_user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # ユーザー削除
  def destroy
    @admin_user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_user
      @admin_user = Admin::User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_user_params
      params.require(:admin_user).permit(:name, :password,:password_confirmation, :title, :mail, :group_id, :admin)
    end
end

app/controllers/users_controller.rb
#coding: utf-8
# UsersController
# Author:: Kazuko Ohmura
# Date:: 2013.07.31

#ユーザ情報更新
class UsersController < PublichtmlController
    before_filter :authorize, :except => :login #ログインしていない場合はログイン画面に移動
    # 更新画面
    def edit
      @user = current_user
    end
  
    # 更新処理
    def update
      @user = current_user
      respond_to do |format|
        if @user.update(user_params)
          @successmsg = {'msg'=>'success'}
          format.html { render action: 'edit' }
          format.json { render json: @successmsg }
        else
          format.html { render action: 'edit' }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
    
    private
      # Never trust parameters from the scary internet, only allow the white list through.
      def user_params
        params.require(:user).permit(:name, :password,:password_confirmation, :title, :mail, :group_id, :admin)
      end
end

app/views/admin/users/_form.html.erb
<div id="setting">
<%= form_for(@admin_user) do |f| %>
  <% if @admin_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_user.errors.count,"error" )%> <%= t('error_user_message') %></h2>

      <ul>
      <% @admin_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :mail %><br>
    <%= f.email_field :mail %>
  </div>
  <div class="field">
    <%= f.label :group_id %><br>
    <%= f.collection_select("group_id",Group.find(:all), :id, :title) %>
  </div>
  <div class="field">
    <%= f.label :admin %><br>
    <%= f.check_box :admin %>
  </div>
  <div class="actions">
    <%= f.submit t('helpers.submit.update'),:class=>"button_admin" %>
  </div>
<% end %>
</div>

app/views/admin/users/edit.html.erb
<%= render 'admin/common/header' %>
<%= render 'admin/common/sidebar' %>
<!-- administrator main content start -->
<div id="content">
<div id="sub_content">
	<h1><%= t('menu_user') %>&nbsp;-&nbsp;<%= t('title_edit') %></h1>
</div>

<%= render 'form' %>

<%= link_to t('title_back'), admin_users_path,:class=>"button_link" %>


</div><!-- administrator main content end -->
<%= render 'admin/common/footer' %>

app/views/admin/users/index.html.erb
<%= render 'admin/common/header' %>
<%= render 'admin/common/sidebar' %>
<!-- administrator main content start -->
<div id="content">
<div id="sub_content">
	
	<h1><%= t('menu_user') %></h1>
</div>

	<table class="coder">
	  <thead>
	    <tr>
	      <th><%= t('title_user_name') %></th>
	      <th><%= t('title_user_title') %></th>
	      <th><%= t('title_group_name') %></th>
	      <th><%= t('title_user_admin') %></th>
	      <th></th>
	    </tr>
	  </thead>
	
	  <tbody>
	    <% @admin_users.each do |admin_user| %>
	      <tr>
	        <td><%= link_to admin_user.name, edit_admin_user_path(admin_user) %></td>
	        <td><%= admin_user.title %></td>
	        <td><%= admin_user.group.title %></td>
	        <td><%= admin_user.admin %></td>
	        <td><%= link_to t('title_delete'), admin_user, method: :delete, data: { confirm: t('message_delete') } %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>

<br />

<% if @admin_users.length < @maxuser %>
<%= link_to t('title_new'), new_admin_user_path,:class=>"button_link" %>
<% end %>


</div><!-- administrator main content end -->
<%= render 'admin/common/footer' %>

app/views/admin/users/new.html.erb
<%= render 'admin/common/header' %>
<%= render 'admin/common/sidebar' %>
<!-- administrator main content start -->
<div id="content">
<div id="sub_content">
	
	<h1><%= t('menu_user') %></h1>
</div>
	<h2><%= t('title_new') %></h2>

<%= render 'form' %>

<%= link_to t('title_back'), admin_users_path,:class=>"button_link" %>


</div><!-- administrator main content end -->
<%= render 'admin/common/footer' %>

app/views/admin/users/show.html.erb
<%= render 'admin/common/header' %>
<%= render 'admin/common/sidebar' %>
<!-- administrator main content start -->
<div id="content">
<div id="sub_content">
	
	<h1><%= t('menu_user') %>&nbsp;-&nbsp;<%= t('title_show') %></h1>
</div>

<p>
  <strong><Name:><%= t('title_user_name') %></strong>
  <%= @admin_user.name %>
</p>

<p>
  <strong><%= t('title_user_title') %></strong>
  <%= @admin_user.title %>
</p>

<p>
  <strong><%= t('title_user_mail') %></strong>
  <%= @admin_user.mail %>
</p>

<p>
  <strong><%= t('title_group_name') %></strong>
  <%= @admin_user.group.title %>
</p>

<p>
  <strong><%= t('title_user_admin') %></strong>
  <%= @admin_user.admin %>
</p>
<br /><br />
<%= link_to t('title_back'), admin_users_path,:class=>"button_link" %>
<%= link_to t('title_edit'), edit_admin_user_path(@admin_user),:class=>"button_link" %>



</div><!-- administrator main content end -->
<%= render 'admin/common/footer' %>