config/routes.rb
#coding: utf-8
# GraphsController
# Author:: Kazuko Ohmura
# Date:: 2013.07.25

Shirokane::Application.routes.draw do
  root 'dashboards#index'
  
  #get "password_resets/new"
  resources :password_resets
  
  resources :login
  resources :users
  resources :graphs do
    member do
      get 'csvexport'
      post 'setday'
    end
  end
  
    # You can have the root of your site routed with "root"
    # root 'welcome#index'
    

  #管理画面用
  namespace :admin do
    resources :login
    resources :users
    resources :graphs
    resources :groups
    resources :home
    resources :settings
    resources :groupgraphs do
      member do
        get 'list'
      end
    end
    root 'home#index'
  end
end

app/views/common/_footer.html.erb
</div><!-- main wrapper end -->
<!-- main footer start -->
<div id="footer">
	<!-- コピーライト / 著作権表示 -->
	<h1>Copyright©SIOS Technology, Inc. All Rights Reserved</h1>
</div><!-- main footer end -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript">
  var htmlHeight = $("html").height();
  var contentHeight = $("#content").innerHeight();
  $(function() {
    if(htmlHeight > contentHeight){
      $("#wrapper").css("height",htmlHeight-150+"px");
      $("#content").css("height",htmlHeight-150+"px");
    }
  });
  $(function() {
    $(window).resize(function(){
      var htmlHeight = $("html").height();
      $("#wrapper").css("height",htmlHeight-150+"px");
      $("#content").css("height",htmlHeight-150+"px");
    });
  });
</script>

app/views/common/_header.html.erb
<!-- main header start -->
<div id="header">
	<div id="logo">
		<h1><%= link_to $settings['title'], root_path %></h1>
	</div>
	<% if current_user != nil %>
	<div id="header_contents">
	  <ul>
	  <li class="user"><i class="icon-user"></i>&nbsp;<%= current_user.title %><span class="group"><%= current_user.group.title %></span></li>
	  <li class="logout">
	  	<%= link_to(login_path(current_user.id), :data =>{:confirm => t('logout_message')}, :method => :delete) do %>
	  	<i class="icon-lock"></i>&nbsp;<%= t('logout') %>
	  	<% end %>
	  </li>
	  <li class="setting"><%= link_to(edit_user_path(current_user.id)) do %><i class="icon-cog"></i><% end %></li>
	  </ul>
	</div>
	<% end %>
</div><!-- main header end -->
<!-- main wrapper start -->
<% if current_user != nil %>
<div id="wrapper">
<% else %>
<div id="wrapper" class="login">
<% end %>

app/views/common/_sidebar.html.erb
<!-- navigation start -->
<div id="navigation">
	<ul class="cds-navi">
		<li<% if params[:controller] == "dashboards" %> class="select"<% end %>><%= link_to(root_path) do %><i class="icon-desktop"></i>&nbsp;<%= t('title_dashboard') %><% end %></li>
		<% current_graph_menu.each do |m| %>
			<li<% if params[:controller] == "graphs" && m.id == @graph.id %> class="select"<% end %>>
				<%= link_to(graph_path(m.id)) do %>
					<% if m.graph_type == 0 %>
					<i class="icon-picture"></i>
					<% else %>
					<i class="icon-bar-chart"></i>
					<% end %>
					&nbsp;<%= m.title %>
				<% end %>
			</li>
		<% end %>
	</ul>
</div><!-- navigation end -->